// Excerpt from `<OUT_DIR>/netchain_bug_s1s2.seq.bpl` (generated by `procurator compile --boogie-harness sequential ...`).
//
// Purpose: provide a small, stable snippet for line-by-line P4 ↔ Boogie alignment docs.
// This is not meant to be a standalone-checkable Boogie program (many declarations are omitted).

// --- Parser: P4 ParserImpl(...) ---
procedure {:inline 1} s1_ParserImpl()
	modifies s1_drop, s1_hdr.ipv4.protocol, s1_hdr.udp.dstPort, s1_isValid, s1_stack.index;
{
    goto s1_State$ParserImpl$start;

        s1_State$ParserImpl$start:
    goto s1_State$ParserImpl$parse_ethernet;

        s1_State$ParserImpl$parse_ethernet:
    call s1_packet_in.extract(s1_hdr.ethernet);
    goto s1_State$ParserImpl$parse_ethernet$parse_ipv4_2, s1_State$ParserImpl$parse_ethernet$DEFAULT;

s1_State$ParserImpl$parse_ethernet$parse_ipv4_2:
    assume (s1_hdr.ethernet.etherType == 2048bv16);
    goto s1_State$ParserImpl$parse_ipv4;

    s1_State$ParserImpl$parse_ethernet$DEFAULT:
    assume(!(s1_hdr.ethernet.etherType == 2048bv16));
    goto s1_State$ParserImpl$accept;

        s1_State$ParserImpl$parse_ipv4:
    call s1_packet_in.extract(s1_hdr.ipv4);
    s1_hdr.ipv4.protocol := 17bv8;
    goto s1_State$ParserImpl$parse_ipv4$parse_tcp_3, s1_State$ParserImpl$parse_ipv4$parse_udp_2, s1_State$ParserImpl$parse_ipv4$DEFAULT;

s1_State$ParserImpl$parse_ipv4$parse_tcp_3:
    assume (s1_hdr.ipv4.protocol == 6bv8);
    goto s1_State$ParserImpl$parse_tcp;

s1_State$ParserImpl$parse_ipv4$parse_udp_2:
    assume (s1_hdr.ipv4.protocol == 17bv8);
    goto s1_State$ParserImpl$parse_udp;

    s1_State$ParserImpl$parse_ipv4$DEFAULT:
    assume(!(s1_hdr.ipv4.protocol == 6bv8)&&!(s1_hdr.ipv4.protocol == 17bv8));
    goto s1_State$ParserImpl$accept;

        s1_State$ParserImpl$parse_nc_hdr:
    call s1_packet_in.extract(s1_hdr.nc_hdr);
    goto s1_State$ParserImpl$parse_nc_hdr$accept_3, s1_State$ParserImpl$parse_nc_hdr$accept_2, s1_State$ParserImpl$parse_nc_hdr$DEFAULT;

s1_State$ParserImpl$parse_nc_hdr$accept_3:
    assume (s1_hdr.nc_hdr.op == 10bv8);
    goto s1_State$ParserImpl$accept;

s1_State$ParserImpl$parse_nc_hdr$accept_2:
    assume (s1_hdr.nc_hdr.op == 12bv8);
    goto s1_State$ParserImpl$accept;

    s1_State$ParserImpl$parse_nc_hdr$DEFAULT:
    assume(!(s1_hdr.nc_hdr.op == 10bv8)&&!(s1_hdr.nc_hdr.op == 12bv8));
    goto s1_State$ParserImpl$accept;

        s1_State$ParserImpl$parse_overlay:
    call s1_packet_in.extract.headers.overlay.next(s1_hdr.overlay);
    goto s1_State$ParserImpl$parse_overlay$parse_nc_hdr_2, s1_State$ParserImpl$parse_overlay$DEFAULT;

s1_State$ParserImpl$parse_overlay$parse_nc_hdr_2:
    assume (s1_hdr.overlay.last.swip == 0bv32);
    goto s1_State$ParserImpl$parse_nc_hdr;

    s1_State$ParserImpl$parse_overlay$DEFAULT:
    assume(!(s1_hdr.overlay.last.swip == 0bv32));
    goto s1_State$ParserImpl$parse_overlay;

        s1_State$ParserImpl$parse_tcp:
    call s1_packet_in.extract(s1_hdr.tcp);
    goto s1_State$ParserImpl$accept;

        s1_State$ParserImpl$parse_udp:
    call s1_packet_in.extract(s1_hdr.udp);
    s1_hdr.udp.dstPort := 8888bv16;
    goto s1_State$ParserImpl$parse_udp$parse_overlay_3, s1_State$ParserImpl$parse_udp$parse_overlay_2, s1_State$ParserImpl$parse_udp$DEFAULT;

s1_State$ParserImpl$parse_udp$parse_overlay_3:
    assume (s1_hdr.udp.dstPort == 8888bv16);
    goto s1_State$ParserImpl$parse_overlay;

s1_State$ParserImpl$parse_udp$parse_overlay_2:
    assume (s1_hdr.udp.dstPort == 8889bv16);
    goto s1_State$ParserImpl$parse_overlay;

    s1_State$ParserImpl$parse_udp$DEFAULT:
    assume(!(s1_hdr.udp.dstPort == 8888bv16)&&!(s1_hdr.udp.dstPort == 8889bv16));
    goto s1_State$ParserImpl$accept;

        s1_State$ParserImpl$accept:

        s1_State$ParserImpl$reject:

    s1_State$accept:
    call s1_accept();
    goto s1_Exit;

    s1_State$reject:
    call s1_reject();
    goto s1_Exit;

    s1_Exit:
}

// --- packet.extract(...) is abstracted as "set header valid" ---
procedure s1_packet_in.extract(s1_header:s1_Ref);
    ensures (s1_isValid[s1_header] == true);
	modifies s1_isValid;

// --- Action: get_sequence_act() ---
procedure {:inline 1} s1_get_sequence_act()
	modifies s1_meta.sequence_md.seq;
{
    // s1_read
        assume (bvule.bv32$builtin(0bv16++s1_meta.location.index, 0bv32));
	s1_meta.sequence_md.seq := s1_sequence_reg.read(s1_sequence_reg, 0bv16++s1_meta.location.index);
}

// --- Action: maintain_sequence_act() (inc + write-back + read-back) ---
procedure {:inline 1} s1_maintain_sequence_act()
	modifies s1_hdr.nc_hdr.seq, s1_meta.sequence_md.seq, s1_sequence_reg, s1_sequence_reg__last_index, s1_sequence_reg__last_value, s1_sequence_reg__wrote_index0, s1_sequence_reg__last0_value;
{
    s1_meta.sequence_md.seq := add.bv16(s1_meta.sequence_md.seq, 1bv16);
    // s1_write
    assume (bvule.bv32$builtin(0bv16++s1_meta.location.index, 0bv32));
    call s1_sequence_reg.write(0bv16++s1_meta.location.index, s1_meta.sequence_md.seq);
    // s1_read
        assume (bvule.bv32$builtin(0bv16++s1_meta.location.index, 0bv32));
	s1_hdr.nc_hdr.seq := s1_sequence_reg.read(s1_sequence_reg, 0bv16++s1_meta.location.index);
}

// --- Action: pop_chain_act() includes pop_front(1) expansion on header stack ---
procedure {:inline 1} s1_pop_chain_act()
	modifies s1_hdr.ipv4.totalLen, s1_hdr.nc_hdr.sc, s1_hdr.overlay.0.swip, s1_hdr.overlay.0.valid, s1_hdr.overlay.1.swip, s1_hdr.overlay.1.valid, s1_hdr.overlay.2.swip, s1_hdr.overlay.2.valid, s1_hdr.overlay.3.swip, s1_hdr.overlay.3.valid, s1_hdr.overlay.4.swip, s1_hdr.overlay.4.valid, s1_hdr.overlay.5.swip, s1_hdr.overlay.5.valid, s1_hdr.overlay.6.swip, s1_hdr.overlay.6.valid, s1_hdr.overlay.7.swip, s1_hdr.overlay.7.valid, s1_hdr.overlay.8.swip, s1_hdr.overlay.8.valid, s1_hdr.overlay.9.valid, s1_hdr.udp.len, s1_isValid;
{
    s1_hdr.nc_hdr.sc := add.bv8(s1_hdr.nc_hdr.sc, 255bv8);
    // s1_pop_front
    s1_hdr.overlay.0.swip := s1_hdr.overlay.1.swip;
    s1_hdr.overlay.0.valid := s1_hdr.overlay.1.valid;
    s1_isValid[s1_hdr.overlay.0] := s1_isValid[s1_hdr.overlay.1];
    s1_hdr.overlay.1.swip := s1_hdr.overlay.2.swip;
    s1_hdr.overlay.1.valid := s1_hdr.overlay.2.valid;
    s1_isValid[s1_hdr.overlay.1] := s1_isValid[s1_hdr.overlay.2];
    s1_hdr.overlay.2.swip := s1_hdr.overlay.3.swip;
    s1_hdr.overlay.2.valid := s1_hdr.overlay.3.valid;
    s1_isValid[s1_hdr.overlay.2] := s1_isValid[s1_hdr.overlay.3];
    s1_hdr.overlay.3.swip := s1_hdr.overlay.4.swip;
    s1_hdr.overlay.3.valid := s1_hdr.overlay.4.valid;
    s1_isValid[s1_hdr.overlay.3] := s1_isValid[s1_hdr.overlay.4];
    s1_hdr.overlay.4.swip := s1_hdr.overlay.5.swip;
    s1_hdr.overlay.4.valid := s1_hdr.overlay.5.valid;
    s1_isValid[s1_hdr.overlay.4] := s1_isValid[s1_hdr.overlay.5];
    s1_hdr.overlay.5.swip := s1_hdr.overlay.6.swip;
    s1_hdr.overlay.5.valid := s1_hdr.overlay.6.valid;
    s1_isValid[s1_hdr.overlay.5] := s1_isValid[s1_hdr.overlay.6];
    s1_hdr.overlay.6.swip := s1_hdr.overlay.7.swip;
    s1_hdr.overlay.6.valid := s1_hdr.overlay.7.valid;
    s1_isValid[s1_hdr.overlay.6] := s1_isValid[s1_hdr.overlay.7];
    s1_hdr.overlay.7.swip := s1_hdr.overlay.8.swip;
    s1_hdr.overlay.7.valid := s1_hdr.overlay.8.valid;
    s1_isValid[s1_hdr.overlay.7] := s1_isValid[s1_hdr.overlay.8];
    s1_hdr.overlay.8.swip := s1_hdr.overlay.9.swip;
    s1_hdr.overlay.8.valid := s1_hdr.overlay.9.valid;
    s1_isValid[s1_hdr.overlay.8] := s1_isValid[s1_hdr.overlay.9];
    s1_hdr.overlay.9.valid := false;
    s1_isValid[s1_hdr.overlay.9] := false;
    s1_hdr.udp.len := add.bv16(s1_hdr.udp.len, 65532bv16);
    s1_hdr.ipv4.totalLen := add.bv16(s1_hdr.ipv4.totalLen, 65532bv16);
}

// --- Ingress apply() structure ---
procedure {:inline 1} s1_ingress()
{
    if(s1_isValid[s1_hdr.nc_hdr]){
        call s1_get_my_address_0.apply();
        if((s1_hdr.ipv4.dstAddr == s1_meta.my_md.ipaddress)){
            call s1_find_index_0.apply();
            call s1_get_sequence_0.apply();
            if((s1_hdr.nc_hdr.op == 10bv8)){
                call s1_read_value_0.apply();
            }
            else{
                if((s1_hdr.nc_hdr.op == 12bv8)){
                    if((s1_meta.my_md.role == 100bv16)){
                        call s1_maintain_sequence_0.apply();
                    }
                    if(((s1_meta.my_md.role == 100bv16)) || ((((sub.bv17(0bv1 ++ s1_hdr.nc_hdr.seq, 0bv1 ++ s1_meta.sequence_md.seq))[17:16] == 0bv1) && (s1_hdr.nc_hdr.seq != s1_meta.sequence_md.seq)))){
                        call s1_assign_value_0.apply();
                        call s1_pop_chain_0.apply();
                    }
                    else{
                        call s1_drop_packet_0.apply();
                    }
                }
            }
            if((s1_meta.my_md.role == 102bv16)){
                call s1_pop_chain_again_0.apply();
                call s1_gen_reply_0.apply();
            }
            else{
                call s1_get_next_hop_0.apply();
            }
        }
    }
    if(s1_isValid[s1_hdr.nc_hdr]){
        call s1_failure_recovery_0.apply();
    }
    if((s1_isValid[s1_hdr.tcp]) || (s1_isValid[s1_hdr.udp])){
        call s1_ipv4_route_0.apply();
    }
}

// --- Distributed harness: enqueue from s1 -> s2 copies only on-wire `hdr.*` fields ---
procedure s1__enqueue_s2() returns()
  modifies s2_hdr.ethernet.etherType, s2_hdr.ethernet.valid, s2_hdr.ipv4.dstAddr, s2_hdr.ipv4.protocol, s2_hdr.ipv4.srcAddr, s2_hdr.ipv4.totalLen, s2_hdr.ipv4.ttl, s2_hdr.ipv4.valid, s2_hdr.nc_hdr.key, s2_hdr.nc_hdr.op, s2_hdr.nc_hdr.sc, s2_hdr.nc_hdr.seq, s2_hdr.nc_hdr.valid, s2_hdr.nc_hdr.value, s2_hdr.nc_hdr.vgroup, s2_hdr.overlay.0.swip, s2_hdr.overlay.0.valid, s2_hdr.overlay.1.swip, s2_hdr.overlay.1.valid, s2_hdr.overlay.2.swip, s2_hdr.overlay.2.valid, s2_hdr.overlay.3.swip, s2_hdr.overlay.3.valid, s2_hdr.overlay.4.swip, s2_hdr.overlay.4.valid, s2_hdr.overlay.5.swip, s2_hdr.overlay.5.valid, s2_hdr.overlay.6.swip, s2_hdr.overlay.6.valid, s2_hdr.overlay.7.swip, s2_hdr.overlay.7.valid, s2_hdr.overlay.8.swip, s2_hdr.overlay.8.valid, s2_hdr.overlay.9.swip, s2_hdr.overlay.9.valid, s2_hdr.overlay.last.swip, s2_hdr.tcp.valid, s2_hdr.udp.dstPort, s2_hdr.udp.len, s2_hdr.udp.valid, s2_inbox_count, s2_pkt_external;
{
  assume s2_inbox_count < 1;
  s2_hdr.ethernet.valid := s1_hdr.ethernet.valid;
  s2_hdr.ethernet.etherType := s1_hdr.ethernet.etherType;
  s2_hdr.ipv4.valid := s1_hdr.ipv4.valid;
  s2_hdr.ipv4.totalLen := s1_hdr.ipv4.totalLen;
  s2_hdr.ipv4.ttl := s1_hdr.ipv4.ttl;
  s2_hdr.ipv4.protocol := s1_hdr.ipv4.protocol;
  s2_hdr.ipv4.srcAddr := s1_hdr.ipv4.srcAddr;
  s2_hdr.ipv4.dstAddr := s1_hdr.ipv4.dstAddr;
  s2_hdr.nc_hdr.valid := s1_hdr.nc_hdr.valid;
  s2_hdr.nc_hdr.op := s1_hdr.nc_hdr.op;
  s2_hdr.nc_hdr.sc := s1_hdr.nc_hdr.sc;
  s2_hdr.nc_hdr.seq := s1_hdr.nc_hdr.seq;
  s2_hdr.nc_hdr.key := s1_hdr.nc_hdr.key;
  s2_hdr.nc_hdr.value := s1_hdr.nc_hdr.value;
  s2_hdr.nc_hdr.vgroup := s1_hdr.nc_hdr.vgroup;
  s2_hdr.tcp.valid := s1_hdr.tcp.valid;
  s2_hdr.udp.valid := s1_hdr.udp.valid;
  s2_hdr.udp.dstPort := s1_hdr.udp.dstPort;
  s2_hdr.udp.len := s1_hdr.udp.len;
  s2_hdr.overlay.last.swip := s1_hdr.overlay.last.swip;
  s2_hdr.overlay.0.valid := s1_hdr.overlay.0.valid;
  s2_hdr.overlay.0.swip := s1_hdr.overlay.0.swip;
  s2_hdr.overlay.1.valid := s1_hdr.overlay.1.valid;
  s2_hdr.overlay.1.swip := s1_hdr.overlay.1.swip;
  s2_hdr.overlay.2.valid := s1_hdr.overlay.2.valid;
  s2_hdr.overlay.2.swip := s1_hdr.overlay.2.swip;
  s2_hdr.overlay.3.valid := s1_hdr.overlay.3.valid;
  s2_hdr.overlay.3.swip := s1_hdr.overlay.3.swip;
  s2_hdr.overlay.4.swip := s1_hdr.overlay.4.swip;
  s2_hdr.overlay.4.valid := s1_hdr.overlay.4.valid;
  s2_hdr.overlay.5.swip := s1_hdr.overlay.5.swip;
  s2_hdr.overlay.5.valid := s1_hdr.overlay.5.valid;
  s2_hdr.overlay.6.swip := s1_hdr.overlay.6.swip;
  s2_hdr.overlay.6.valid := s1_hdr.overlay.6.valid;
  s2_hdr.overlay.7.swip := s1_hdr.overlay.7.swip;
  s2_hdr.overlay.7.valid := s1_hdr.overlay.7.valid;
  s2_hdr.overlay.8.swip := s1_hdr.overlay.8.swip;
  s2_hdr.overlay.8.valid := s1_hdr.overlay.8.valid;
  s2_hdr.overlay.9.valid := s1_hdr.overlay.9.valid;
  s2_hdr.overlay.9.swip := s1_hdr.overlay.9.swip;
  s2_pkt_external := false;
  s2_inbox_count := s2_inbox_count + 1;
}
