// Unified build source file. Generated by CMake. DO NOT EDIT.
#include "frontends/p4/typeChecking/typeUnification.cpp"
#include "frontends/p4/typeMap.cpp"
#include "frontends/p4/uniqueNames.cpp"
#include "frontends/p4/unusedDeclarations.cpp"
#include "frontends/p4/uselessCasts.cpp"
#include "frontends/p4/validateParsedProgram.cpp"
#include "frontends/p4-14/typecheck.cpp"
#include "frontends/p4-14/header_type.cpp"
